### ISSUE TITLE
Lightning address camelCase sensitive

### ISSUE THREAD

**Issue by seaKyou1** [Dolu89/ligess#11]
I noticed that, unlike email addresses, with ligess lightning addresses are currently camelCase sensitive, meaning that if I configure the ligess server such that LIGESS_USERNAME=dolu & LIGESS_DOMAIN=bips.xyz, for some clients (e.g. Amethyst and Zeus) I will not be able to receive invoices for DoLu@biPs.xyz. 

For other clients such (e.g. WalletOfSatoshi) this issue does not exist. This makes me wonder whether this issue should be addressed on the client side (wallet app) or on the server side (ligess).

**Comment by Dolu89** [comment]
It's my personal opinion, but it could be great for ligess (and all other ln address providers) to not be case sensitive.
DoLu@biPs.xyz should work if configured as dolu@bips.xyz in ligess or configured as DOLU@BIPS.XYZ

**Comment by seaKyou1** [comment]
> It's my personal opinion, but it could be great for ligess (and all other ln address providers) to not be case sensitive. [DoLu@biPs.xyz](mailto:DoLu@biPs.xyz) should work if configured as [dolu@bips.xyz](mailto:dolu@bips.xyz) in ligess or configured as [DOLU@BIPS.XYZ](mailto:DOLU@BIPS.XYZ)

Lightning address being case sensitive can be beneficial too. In my humble opinion it would be better for the ecosystem to just follow the example of email addresses to not confuse people.

This said, my .env is configured as follows:
LIGESS_USERNAME=seak
LIGESS_DOMAIN=https://lnd.satoshibox.org

Unfortunately, neither Zeus nor Amethyst like seaK@ln.satoshiBox.org (as an example). I guess the issue is on their side then. Thank you for your feedback!
