### ISSUE TITLE
[Feature] support multiple usernames (addresses)

### ISSUE THREAD

**Issue by danielcharrua** [Dolu89/ligess#14]
Would be great to use this package with multiple addresses, use cases: for a company, group of individuals or family/friends.

Maybe add multiple users in .env and iterate them creating the fastify get routes.

`LIGESS_USERNAMES="user1, user2, user3"`

Then get those values using `_usernames = process.env.LIGESS_USERNAMES.split(", ");`

Don't know how to create the part to iterate and create the get routes but maybe using a simple forEach

```
_usernames.forEach(user => fastify.get('/.well-known/lnurlp/:user', async (request, reply) => {
```

**Comment by Dolu89** [comment]
You don't need to create multiple routes, only one is enough with a dynamic param like you did `/:user`
If multiple user is added, multiple node should be added too, or you want all ln address on the same node?

**Comment by danielcharrua** [comment]
> You don't need to create multiple routes, only one is enough with a dynamic param like you did /:user

You are right, `:username` is a dynamic parameter in the route, so no need for more routes.

> If multiple user is added, multiple node should be added too, or you want all ln address on the same node?

Thats a really good question 🤔 what are your thoughts on this matter? Any pros/cons?

**Comment by Dolu89** [comment]
Ligess is a personal server, so it was supposed to be a one ln address provider. If you want multiple addresses with multiple nodes, maybe you should use satdress. 

Now, if adding multiple addresses, but not multiple nodes, what is the interest if a@domain.com and b@domain.com are on the same node? Is it not better to have a unique address like donate@domain.com instead?

**Comment by danielcharrua** [comment]
Makes sense! So Ligess for personal use and satdress for multiple users each one with their own lightning address and node.

Thank you!
