### ISSUE TITLE
nginx documentation

### ISSUE THREAD

**Issue by seth586** [Dolu89/ligess#6]
I'll be the first to admit I suck configuring nginx... Could we get a recommended nginx documentation to serve ligess?

Right now I have a location block with proxy_pass to ligess in `nginx.conf`:
```
location /.well-known/lnurlp {
                        proxy_pass http://127.0.0.1:3000/;
                        default_type "text/plain";
                }
```

Response from accessing `https://redactedmydomain.com/.well-known/lnurlp`:
```
{"lnurlp":"lnurl1dp68gurn8ghj7mt8d4cx7mmv9eh8jmfwd9kj6tnhv4kxctttdehhwm66d3h82unjwqhhxet3dq6nsdsenadmc","decodedUrl":"https://redactedmydomain/.well-known/lnurlp/seth586","info":{"title":"Ligess: Lightning address personnal server","source":"https://github.com/dolu89/ligess"}}
```

However my response from accessing `https://redactedmydomain.com/.well-known/lnurlp/seth586`:
```
{"message":"Route GET://seth586 not found","error":"Not Found","statusCode":404}
```

**Comment by seth586** [comment]
I changed my `nginx.conf` location block to:
```
location /.well-known/lnurlp/seth586 {
                        proxy_pass http://127.0.0.1:3000/;
                }
```
But the response is throwing an error with bluewallet when trying to pay to my lightning address- "lnurl-pay expected, found tag undefined"

**Comment by Dolu89** [comment]
I'm not an nginx user so I can't help you on this config.
You can try this maybe? https://twitter.com/mutatrum/status/1517151400349687809?t=anPTObUpaUE2R2Da3yQaQg
cc @mutatrum

**Comment by seth586** [comment]
That fixed it, the forward slash should not trail the proxy_pass line, thank you!

Working nginx block:
```
                location /.well-known/lnurlp/seth586 {
                        proxy_pass http://127.0.0.1:3000;
                }
```
