### ISSUE TITLE
[Feature] Add support for Nostr Zaps

### ISSUE THREAD

**Issue by mutatrum** [Dolu89/ligess#8]
See https://github.com/nostr-protocol/nips/blob/master/57.md for the specifications of Nostr Zaps.

**Comment by mutatrum** [comment]
I can take a stab at implementing this, but it'll add some Nostr specific code. I can also fork this repo and make it a ligess/nostr spinoff.

**Comment by Dolu89** [comment]
I'm ok with adding Nostr Zaps in this repo.
I never played with Zaps, yet. So if you want to add it yourself, go!

**Comment by Dolu89** [comment]
Done in #9
